default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: china64
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
  database: portfolio_production
  username: portfolio
  password: china64
